- .circleci/config.yml
- README.md
- config/stripes.config.js
- karma.conf.js
- package.json
- script/js/build.js
- src/components/Lib/Message/EmptyMessage.css
- src/redux/helpers/index.js
- src/utils/Constant.js
fix warning dependencies and some wrong config
> fix warning dependencies and some wrong config

- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
> fix search details

- src/index.js
- src/redux/index.js
- src/settings/components/DefaultTemplate.js
- src/settings/components/FieldGroupings.js
- src/settings/components/LocalAuthorityRecords.js
- src/settings/components/RecordOverlayRules.js
- src/settings/components/Settings.js
- src/settings/index.js
- translations/ui-marccat/en.json
> add settings page

- src/components/Search/Filter/FiltersContainer.js
- src/components/Search/Result/RecordDetails.js
- src/components/Search/Result/SearchResults.js
- src/redux/reducers/Reducer.js
> add dynamic recordType filters in result search

- src/components/Search/Result/SearchResults.js
- src/redux/actions/ActionCreator.js
- src/redux/epic/epics.js
- src/redux/reducers/Reducer.js
> fix results counter

- src/components/Search/Filter/FiltersContainer.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Select/FilterMapper.js
- src/components/Search/Utils/Mapper.js
- src/redux/actions/ActionCreator.js
- src/redux/epic/epics.js
- src/redux/index.js
- src/redux/reducers/Reducer.js
fix search call and icons when fetching data
> fix search call now for both records and restore icons when fetching data

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/pt_BR.json
> Update translation strings as of 20181128T202334

- src/components/Search/Result/SearchPanel.js
> folio-emptyAuthQuery case

- package.json
- src/lib/ActionMenu/ActionMenu.js
- src/lib/index.js
- src/settings/components/DefaultTemplate.js
> add actionmenu and button

- src/index.js
- src/settings/components/MarcatSettings.js
- src/settings/index.js
> fix wrong import

- src/settings/components/LocalAuthorityRecords.js
- src/settings/components/RecordOverlayRules.js
> add button to settings button

- src/styles/common.css
fix wrong width on auth record
> fix wrong width on auth record

- src/components/Search/Result/SearchResults.js
- src/lib/Style/InputField.css
- src/lib/components/ActionMenu/ActionMenu.js
- src/lib/components/Button/OptionButton.js
- src/lib/components/Formatter/DefaultFormatter.js
- src/utils/Formatter.js
fix checked handler and start hide/show column feature
> fix checked handler and start hide/show column feature

- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/utils/Constant.js
> fix-update

- package.json
- src/components/Cataloguing/MarcRecord.js
> fix package json

- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/MarcRecord.js
> mapping leader display value

- src/components/Cataloguing/Marc/FixedFields.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Cataloguing/MarcRecord.js
- src/core/api/StoreService.js
fix tenant in save bibliographic record
> fix tenant in save bibliographic record

- src/components/Cataloguing/MarcRecord.js
- src/components/Cataloguing/Utils/MarcUtils.js
- src/core/api/StoreService.js
- src/lib/components/Toolbar/Menu.js
- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
> add delete record

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/Marc/Buttons/MarcPaneMenu.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
> fix complex query form remove

- config/stripes.config.js
remove redux log categories in production env
> remove redux log categories in production env

- config/stripes.config.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/FixedFields.js
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Search/Result/SearchResults.js
- src/redux/epic/epic.js
- src/redux/helpers/StoreReducer.js
> fix variable fields crash

- src/components/Browse/Result/BrowseResults.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/components/SearchResultPane.js
- src/components/Search/index.css
- src/utils/Formatter.js
> add filter for complex query

- config/stripes.config.js
- src/components/Browse/Result/BrowseItemDetail.js
- src/components/Browse/Result/BrowseResults.js
- src/components/Browse/Result/components/ResultDetailPane.js
- src/components/Browse/Result/components/ResultMainPane.js
- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/Marc/MarcLeader.js
- src/lib/components/ActionMenu/ActionMenu.js
- src/redux/epic/epic.js
- src/redux/helpers/Action.js
- src/redux/helpers/Dispatcher.js
- src/redux/helpers/StoreReducer.js
- src/router.js
> fix search

- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/zh_CN.json
> Update translation strings as of 20190130T201814

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Result/components/RecordDetailPane.js
- src/index.js
- src/router.js
- src/utils/Constant.js
- translations/ui-marccat/en.json
> fix create record and view 

- src/components/Search/Filter/FiltersContainer.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Result/components/SearchResultPane.js
- src/utils/Formatter.js
fix in search column and filter
> fix in search column and filter

- translations/ui-marccat/en_US.json
> Update translation strings as of 20190225T222207

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
> update cataloging 008 tag

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Search/Result/SearchPanel.js
- src/utils/Constant.js
> add tags to cataloging wf

- script/js/build.js
- src/MARCcat.js
- src/components/Browse/Result/BrowseItemDetail.js
- src/components/Browse/Result/BrowseResults.js
- src/components/Browse/Result/components/ResultDetailPane.js
- src/components/Browse/Result/components/ResultMainPane.js
- src/components/Cataloguing/Actions/MarcActionCreator.js
- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/Editable/MarcRecordListForm.js
- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag006.js
- src/components/Cataloguing/Marc/Tags/Tag007.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Cataloguing/Utils/Constant.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
- src/components/Cataloguing/Utils/MarcUtils.js
- src/components/Search/Result/AssociatedBib.js
- src/components/Search/Result/RecordDetails.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Result/components/AssociatedRecordPane.js
- src/components/Search/Utils/SearchUtils.js
- src/core/hoc/withBind.js
- src/core/hoc/withInjection.js
- src/redux/epic/epic.js
- src/redux/index.js
- src/utils/Constant.js
- src/utils/Mapper.js
> update headin and tag008

- src/components/Browse/Result/components/ResultDetailPane.js
- src/components/Browse/Result/components/ResultMainPane.js
- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/index.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Select/SearchIndexes.js
- src/components/Search/Utils/Constant.js
- src/components/Search/Utils/SearchUtils.js
- src/core/hoc/withBind.js
- src/redux/epic/epic.js
- src/redux/helpers/Dispatcher.js
- src/shared/Constants.js
replace search vertical call API with new generic epic call
> replace search vertical call API with new generic epic call

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Cataloguing/Utils/MarcUtils.js
add subfiled replace in read and view operation
> add subfiled replace in read and view operation

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag00X.js
- src/components/Cataloguing/Utils/MarcUtils.js
replace all $ char in tag display value
> replace all $ char in tag display value

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/Marc/FixedFields.js
- src/components/Cataloguing/Marc/MarcField.js
- src/components/Cataloguing/Utils/MarcUtils.js
> add 006-007 first release

- translations/ui-marccat/pt_BR.json
> Update translation strings as of 20190327T171657

- src/components/Cataloguing/Marc/Tags/Tag008.js
> tag008 displayValue onChange

- src/components/Cataloguing/Actions/MarcActionCreator.js
- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag006.js
- src/components/Cataloguing/Marc/Tags/Tag007.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
- src/components/Cataloguing/Utils/MarcUtils.js
- src/components/Search/Actions/ActionCreator.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/redux/actions/ActionCreator.js
- src/redux/epic/epics.js
- src/redux/helpers/StoreReducer.js
- src/redux/index.js
- src/redux/reducers/Reducer.js
> fix leader and add modify

- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/components/SearchResultPane.js
change specific values of leader automatically update headerType of tag 008 and his values
> restore leader and 008

- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
fix 008 displayValue and leader actions
> fix 008 displayValue and leader actions

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/Editable/MarcRecordListForm.js
- src/components/Cataloguing/Marc/FixedFields.js
- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag006.js
- src/components/Cataloguing/Marc/Tags/Tag007.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
- src/components/Cataloguing/Utils/MarcConstant.js
- src/components/Cataloguing/index.js
- src/components/Search/Actions/ActionCreator.js
- src/core/index.js
- src/core/type/index.js
> start cataloging refactoring

- src/components/Cataloguing/Marc/MarcLeader.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
> final fix 000 and 008

- translations/ui-marccat/ar.json
- translations/ui-marccat/en_US.json
> Update translation strings as of 20190403T132033

- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/Marc/Editable/MarcRecordListForm.js
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
- src/components/Search/Actions/ActionCreator.js
- src/redux/epic/epics.js
> massive fix

- src/components/Cataloguing/Actions/MarcActionCreator.js
- src/components/Cataloguing/CreateMarcRecord.js
- src/components/Cataloguing/EditMarcRecord.js
- src/components/Cataloguing/MarcRecord.js
start common file for cataloging
> start common file for cataloging

- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
fix new version of cataloging variable field
> fix new version of cataloging variable field

- src/components/Search/Result/RecordDetails.js
- src/shared/Constants.js
some fix after test third panel
> some fix after test third panel

- src/components/Search/Result/RecordDetails.js
> fix details panel

- src/components/Search/Result/SearchPanel.js
add index for query publisher place
> add index for query publisher place

- src/components/Cataloguing/Marc/Editable/MarcRecordListForm.js
- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Search/Result/RecordDetails.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Utils/SearchUtils.js
- src/router.js
- src/shared/Constants.js
> add modify for cataloguing

- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Cataloguing/Marc/Tags/Tag006.js
- src/components/Cataloguing/Marc/Tags/Tag007.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
- src/components/Cataloguing/Utils/MarcConstant.js
- src/components/Cataloguing/index.js
- src/components/Search/Result/RecordDetails.js
- src/components/Search/Result/SearchResults.js
fix details panel and fix display value
> fix details panel and fix display value

- src/components/Cataloguing/Marc/Editable/MarcRecordListForm.js
- src/components/Cataloguing/Marc/MarcRecord.js
- translations/ui-marccat/en.json
> fix save record

- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Cataloguing/Utils/MarcApiUtils.js
> fix message

- package.json
- script/deploy.sh
- src/components/Cataloguing/Marc/ActionsMenu.js
- src/components/Cataloguing/Marc/Editable/MarcItemEdit.js
- src/components/Cataloguing/Marc/Editable/MarcRecordListForm.js
- src/components/Cataloguing/Marc/FixedFields.js
- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Cataloguing/Marc/Tags/Tag007.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Search/Actions/index.js
- src/components/Search/History/PanelHistory.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Result/components/AssociatedRecordPane.js
- src/lib/Style/Dropdown.css
- src/lib/components/ActionMenu/ActionMenu.js
- src/lib/components/Button/DropdownButtonMenu.js
- src/redux/epic/epic.js
- src/redux/helpers/Redux.js
- src/redux/index.js
- src/router.js
- src/settings/components/DefaultTemplate.js
- src/settings/components/RecordOverlayRules.js
- src/shared/Action.js
- src/shared/Function.js
- translations/ui-marccat/en.json
> histiry panel

- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Cataloguing/Marc/Tags/Tag006.js
> fix tag006 and double dollar in detail panel search

- package.json
- src/components/Cataloguing/Marc/VariableFields.js
- src/components/Search/Actions/index.js
- src/components/Search/History/ClearHistory.js
- src/components/Search/History/PanelHistory.js
- src/components/Search/Result/SearchPanel.js
- src/components/Search/Utils/SearchUtils.js
- src/lib/Style/Dropdown.css
- src/redux/epic/epic.js
- src/shared/Action.js
- translations/ui-marccat/en.json
> search history

- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Cataloguing/Marc/Tags/Tag008.js
> fix tag 008

- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Search/Button/DuplicaRecord.js
> fix duplica record

- src/components/Cataloguing/Actions/index.js
- src/components/Cataloguing/Marc/Fixed/FixedFields.js
- src/components/Cataloguing/Marc/Fixed/Tags/Tag008.js
- src/components/Cataloguing/Marc/MarcRecord.js
- src/components/Settings/components/DefaultTemplate.js
- src/shared/config/constants.js
> merge fix 008

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/zh_CN.json
> Update translation strings as of 20190426T133506

- translations/ui-marccat/es_ES.json
- translations/ui-marccat/pt_BR.json
> Update translation strings as of 20190429T154045

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/zh_CN.json
> Update translation strings as of 20190503T205536

- translations/ui-marccat/pt_BR.json
> Update translation strings as of 20190507T141001

- README.md
> remove badge circle ci

- src/components/Browse/BrowseResults.js
- src/shared/utils/Formatter.js
> fix update crossRef

- src/components/Cataloguing/Marc/Form/DataField/index.js
- src/components/Cataloguing/Marc/Record/index.js
> add padding to date 008

- src/components/Browse/BrowseItemDetail.js
- src/components/Browse/BrowseResults.js
- src/components/Search/Style/index.css
> final cross references update fix

- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/zh_CN.json
> Update translation strings as of 20190517T183537

- src/components/Cataloguing/Actions/index.js
- src/components/Cataloguing/Marc/Form/VariableField/FieldEdit.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestCode.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestInd1.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestInd2.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestion.js
- src/config/constants.js
> fix and close crossreference 

- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
> Update translation strings as of 20190609T200038

- translations/ui-marccat/ar.json
> Update translation strings as of 20190627T152539

- src/components/Search/Result/components/SearchResultMapper.js
- src/shared/utils/Formatter.js
> fix for sonarCloud

- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
> more sonarcloud fix

- config/stripesclirc.config.js
> sonar test

- src/components/Browse/BrowseResults.js
> fix sonar in browse function

- src/components/Search/Panel/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/shared/utils/Arrays.js
> fix sonar cloud in master

- translations/ui-marccat/it_IT.json
> Update translation strings as of 20190711T172340

- CHANGELOG.md
- package.json
- src/components/Cataloguing/Actions/index.js
- src/components/Cataloguing/Marc/Record/index.js
- src/components/Settings/components/DefaultTemplate.js
- src/config/constants.js
- src/redux/epic/epic.js
- src/shared/utils/Function.js
> Release v1.8.5

- translations/ui-marccat/it_IT.json
> Update translation strings as of 20190925T125755

- config/stripesclirc.config.js
- package.json
- src/config/constants.js
- src/shared/utils/Function.js
> fix in dependencies

- package.json
removed resolutions block in package.json
> removed resolutions block

- config/stripesclirc.config.js
- src/config/constants.js
- src/redux/epic/epic.js
- src/shared/utils/Function.js
> fix tenant

- config/stripesclirc.config.js
- src/config/constants.js
- src/redux/epic/epic.js
- src/shared/utils/Function.js
> fix tenant and token okapi

- src/config/constants.js
- src/redux/epic/epic.js
- src/redux/epic/epics.js
> fix for tenant

- config/stripesclirc.config.js
- src/config/constants.js
- src/redux/epic/epic.js
- src/shared/utils/Function.js
> fix in url path

- config/stripesclirc.config.js
> fix okapiurl

- Jenkinsfile
> fix new version

- config/stripesclirc.config.js
- src/components/Cataloguing/Marc/Record/index.js
- src/config/constants.js
- src/redux/epic/epic.js
- src/shared/utils/Function.js
> fix tenant and token

- package.json
- src/components/Cataloguing/Marc/Record/Tags/FixedField.js
- src/components/Cataloguing/Marc/Record/index.js
- src/components/Search/Result/components/SearchResultPane.js
- src/shared/lib/Button/OptionButton.js
> fix in search css and update some dependencies

- src/components/Search/Result/components/SearchResultPane.js
- src/redux/epic/epic.js
- src/redux/epic/epics.js
> update all calls

- translations/ui-marccat/ja.json
> Update translation strings as of 20191101T131808

- translations/ui-marccat/ru.json
> Update translation strings as of 20191113T152522

- src/components/Cataloguing/Marc/Form/VariableField/FieldForm.js
> fix edit tag

- src/components/Cataloguing/Marc/Form/VariableField/FieldForm.js
remove HotKeys - temporary fix
> remove HotKeys - temporary fix

- src/components/Cataloguing/Marc/Form/VariableField/FieldForm.js
fix onAdd and onAddAbove in editTag
> fix onAdd and onAddAbove

- src/components/Cataloguing/Marc/Form/VariableField/FieldEdit.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
> fix delimitator in autoSuggestionHeadings

- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
> fix crash autosuggest

- src/components/Cataloguing/Marc/Form/VariableField/FieldForm.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
fix case sensitive in HotKeys component
> fix case sensitive in HotKeys component

- package.json
- src/components/Cataloguing/Marc/Record/Leader.js
- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
fix controlledField leader 008
> fix controlledField leader 008

- src/components/Cataloguing/Marc/Record/index.js
crash app after save record failed
> fix: crash app after save record failed

- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
> fix: wrong displayValue length

- src/shared/utils/Formatter.js
> fix: small fix customColumns

- translations/ui-marccat/ar.json
> Update translation strings as of 20200103T213225

- src/components/Search/History/PanelHistory.js
search call in history search panel
> search call in history search panel

- src/components/Search/History/PanelHistory.js
> fix call from history panel

- translations/ui-marccat/en_US.json
> Update translation strings as of 20200127T144839

- src/components/Search/History/PanelHistory.js
- src/components/Search/Panel/SearchPanel.js
> sortType in search history

- src/components/Cataloguing/Marc/Form/DataField/index.js
- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
> fix: uicat-4-68

- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
- src/components/Cataloguing/Marc/Record/index.js
- src/components/Search/History/PanelHistory.js
fix: panelHistory search and subfield check on create heading
> fix: panelHistory search and subfield check on create heading

- src/components/Cataloguing/Marc/Record/index.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestion.js
> ind1 ind2 restore prev vers

- translations/ui-marccat/fr_FR.json
> Update translation strings as of 20200206T141023

- src/components/Cataloguing/Marc/Suggestion/AutoSuggestion.js
- src/components/Search/Result/SearchResults.js
fix: details for publisher index and fiz digit on ind1-ind2
> fix: details for publisher index and fiz digit on ind1-ind2

- src/components/Browse/BrowseResults.js
> fix: lint and browse details

- src/components/Cataloguing/Marc/Record/index.js
- src/components/Search/Button/DuplicateRecord.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Result/components/RecordDetailPane.js
- src/shared/utils/Formatter.js
> fix: UICAT-74

- src/components/Cataloguing/Marc/Record/index.js
- src/components/Search/History/PanelHistory.js
- src/components/Search/Panel/SearchPanel.js
- src/components/Search/Result/components/SearchResultPane.js
- src/redux/actions/ActionCreator.js
- src/redux/epic/epics.js
- src/redux/reducers/Reducer.js
filters and sortType when record comes from cataloging
> Fix: filters and sortType when record comes from cataloging

- translations/ui-marccat/fr_FR.json
> Update translation strings as of 20200224T151433

- src/components/Browse/BrowseResults.js
- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
- src/components/Search/Button/EditRecord.js
- src/components/Search/Result/SearchResults.js
browse actionMenuButton and fix in visualRunningTime tag 008
> fix: UICAT-73

- src/components/Browse/BrowseResults.js
- src/components/Cataloguing/Marc/Menu/ActionLabels.js
- src/components/Search/Panel/SearchPane.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Result/components/SearchResultPane.js
- src/shared/utils/Formatter.js
cuctom column select in search
> cuctom column select in search

- src/components/Browse/BrowseItemDetail.js
- src/components/Browse/BrowseResults.js
- src/components/Search/Result/SearchResults.js
some fix for UICAT-78 and UICAT-80
> some fix for UICAT-78 and UICAT-80

- translations/ui-marccat/ru.json
> Update translation strings as of 20200312T133304

- package.json
- src/components/Search/Panel/SearchPanel.js
update stripes dependencies and fix UICAT-82
> update stripes dependencies and fix UICAT-82

- package.json
update dependencies for react-hotkeys
> fix: UICAT-63 update dependencies for react-hotkeys

- src/components/Cataloguing/Actions/index.js
- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
- src/components/Cataloguing/Marc/Record/index.js
> edit leader and tag 008

- src/components/Cataloguing/Marc/Form/DataField/index.js
- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
- src/components/Cataloguing/Utils/MarcConstant.js
> MODCAT-171

- translations/ui-marccat/pt_BR.json
> Update translation strings as of 20200409T134057

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/he.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/ja.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/ru.json
- translations/ui-marccat/ur.json
- translations/ui-marccat/zh_CN.json
- translations/ui-marccat/zh_TW.json
> Update translation strings as of 20200519T123842

- translations/ui-marccat/fr_FR.json
> Update translation strings as of 20200604T202430

- src/components/Browse/BrowseResults.js
- src/components/Cataloguing/Actions/index.js
- src/components/Cataloguing/Marc/Record/Tags/FixedField.js
- src/components/Cataloguing/Marc/Record/Tags/Tag006.js
- src/components/Cataloguing/Marc/Record/Tags/Tag007.js
- src/components/Cataloguing/Marc/Record/Tags/Tag00X.js
- src/components/Cataloguing/Marc/Record/index.js
- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
- src/components/Cataloguing/Style/index.css
- src/components/Cataloguing/Utils/MarcConstant.js
- src/components/Search/Button/EditRecord.js
- src/config/constants.js
- src/redux/epic/epics.js
- src/shared/utils/Function.js
> some bug fix and update

- translations/ui-marccat/en.json
> fix button remove tag

- src/components/Search/Panel/components/Bracket.js
- src/components/Search/Result/components/SearchResultMapper.js
- src/redux/epic/epic.js
- src/shared/utils/Formatter.js
> sonar fix duplications

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/he.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/ja.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/ru.json
- translations/ui-marccat/ur.json
- translations/ui-marccat/zh_CN.json
- translations/ui-marccat/zh_TW.json
> Update translation strings as of 20200615T161518

- translations/ui-marccat/ru.json
> Update translation strings as of 20200615T202100

- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
> small fix validateTag

- src/components/Cataloguing/Marc/Suggestion/AutoSuggestHeadings.js
- src/components/Search/Select/SearchIndexes.js
> fix sortBy all MARC

- translations/ui-marccat/fr_FR.json
> Update translation strings as of 20200716T140311

- translations/ui-marccat/zh_CN.json
> Update translation strings as of 20200721T202356

- src/components/Browse/BrowseResults.js
- src/redux/epic/epics.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/browse-search.js
- test/bigtest/network/factories/heading.js
- test/bigtest/network/models/browse-search.js
- test/bigtest/network/models/heading.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/network/serializers/browse-search.js
- test/bigtest/tests/browse-test.js
- test/bigtest/tests/search-test.js
fix browse result for browse-test
> fix browse result for browse-test

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/he.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/ja.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/ru.json
- translations/ui-marccat/ur.json
- translations/ui-marccat/zh_CN.json
- translations/ui-marccat/zh_TW.json
> Update translation strings as of 20200817T131718

- translations/ui-marccat/pt_BR.json
> Update translation strings as of 20200901T173106

- CHANGELOG.md
- src/components/Browse/BrowseResults.js
- src/components/Search/Actions/index.js
- src/components/Search/Filter/FilterMapper.js
- src/components/Search/Filter/ResetButton/ResetButton.css
- src/components/Search/Filter/ResetButton/ResetButton.js
- src/components/Search/Panel/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/config/constants.js
- src/redux/actions/ActionCreator.js
- src/redux/actions/Actions.js
- src/redux/epic/epics.js
- src/redux/index.js
- src/redux/reducers/Reducer.js
- src/shared/utils/Formatter.js
- test/bigtest/interactors/search.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/authority-search.js
- test/bigtest/network/factories/bib-search.js
- test/bigtest/network/factories/docauth.js
- test/bigtest/network/factories/docbib.js
- test/bigtest/network/models/authority-search.js
- test/bigtest/network/models/bib-search.js
- test/bigtest/network/models/docauth.js
- test/bigtest/network/models/docbib.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/network/serializers/authority-search.js
- test/bigtest/network/serializers/bib-search.js
- test/bigtest/tests/search-test.js
- translations/ui-marccat/en.json
- [UICAT-106 Search authority records](https://issues.folio.org/projects/UICAT/issues/UICAT-106)
- [UICAT-112 Add option to reset all in the search](https://issues.folio.org/projects/UICAT/issues/UICAT-112)
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> Uxprod 2613

- CHANGELOG.md
- src/shared/lib/Message/NoResultsMessage.js
- src/shared/lib/Style/EmptyMessage.css
- src/shared/lib/Style/NoResultsMessage.css
- translations/ui-marccat/en.json
Change the panel of 'No results found' to be similar as other apps
- [UICAT-113 Change the panel of 'No results found'](https://issues.folio.org/projects/UICAT/issues/UICAT-113)
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UICAT-113 Change the panel of 'No results found'

- translations/ui-marccat/ru.json
- translations/ui-marccat/zh_CN.json
> Update translation strings as of 20200928T202231

- translations/ui-marccat/fr_FR.json
> Update translation strings as of 20201005T202004

- src/components/Browse/BrowseResults.js
- test/bigtest/interactors/action-menu.js
- test/bigtest/interactors/browse.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/heading.js
- test/bigtest/tests/action-menu-test.js
- test/bigtest/tests/browse-test.js
Update tests for browse details and actionMenu
> Update tests for browse details and actionMenu

- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
> Update translation strings as of 20201016T144229

- CHANGELOG.md
- src/components/Cataloguing/Actions/index.js
- src/components/Cataloguing/Marc/Record/index.js
- src/components/Search/Actions/index.js
- src/components/Search/Button/DuplicateRecord.js
- src/components/Search/Button/EditRecord.js
- src/components/Search/Panel/SearchPanel.js
- src/components/Search/Result/SearchResults.js
- src/components/Search/Result/components/SearchResultPane.js
- src/config/constants.js
- src/flow/actionTypes.js.flow
- src/redux/actions/Actions.js
- src/redux/reducers/Reducer.js
- test/bigtest/interactors/action-menu.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/fixed-fields-code-group.js
- test/bigtest/network/factories/fixedFieldsCodeGroupsByLeader.js
- test/bigtest/network/factories/from-auth-template.js
- test/bigtest/network/factories/header-type.js
- test/bigtest/network/models/fixed-fields-code-group.js
- test/bigtest/network/models/fixedFieldsCodeGroupsByLeader.js
- test/bigtest/network/models/from-auth-template.js
- test/bigtest/network/models/header-type.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/network/serializers/fixed-fields-code-group.js
- test/bigtest/network/serializers/fixedFieldsCodeGroupsByLeader.js
- test/bigtest/network/serializers/from-auth-template.js
- test/bigtest/network/serializers/header-type.js
- test/bigtest/tests/action-menu-test.js
- [UICAT-114 Create new authority using a template by default](https://issues.folio.org/browse/UICAT-114)
In the first load of marccat, is loading a template for Bibs records, now we load a template for Auth records too.
Bibliographic template: /marccat/bibliographic-record/from-template/1
Authority template: /marccat/authority-record/from-template/1
In search we have to select Bibs or Auth record, and then we have to select New record in Actions menu.
We manage "segmentActive" to know which option is selected and manage wich api calls to do and wich options we have to show.
If there are breaking …
> UICAT-114 Create new authority using a template by default

- src/components/Browse/BrowseAssociatedItemDetail.js
- src/components/Browse/BrowseItemDetail.js
- src/components/Search/Result/RecordDetails.js
- src/components/Search/Result/components/RecordDetailPane.js
- src/components/Search/Result/components/SearchResultPane.js
- test/bigtest/interactors/browse.js
- test/bigtest/interactors/search.js
- test/bigtest/tests/browse-test.js
- test/bigtest/tests/search-test.js
> update browse test 

- translations/ui-marccat/ar.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/he.json
- translations/ui-marccat/hi_IN.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/ja.json
- translations/ui-marccat/ko.json
- translations/ui-marccat/pl.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/ru.json
- translations/ui-marccat/ur.json
- translations/ui-marccat/zh_CN.json
- translations/ui-marccat/zh_TW.json
> Update translation strings as of 20201026T135354

- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/ja.json
> Update translation strings as of 20201105T151643

- translations/ui-marccat/fr_FR.json
> Update translation strings as of 20201110T192302

- translations/ui-marccat/it_IT.json
> Update translation strings as of 20201111T142927

- translations/ui-marccat/ar.json
- translations/ui-marccat/ber.json
- translations/ui-marccat/ca.json
- translations/ui-marccat/da.json
- translations/ui-marccat/de.json
- translations/ui-marccat/en_GB.json
- translations/ui-marccat/en_SE.json
- translations/ui-marccat/en_US.json
- translations/ui-marccat/es.json
- translations/ui-marccat/es_419.json
- translations/ui-marccat/es_ES.json
- translations/ui-marccat/fr.json
- translations/ui-marccat/fr_FR.json
- translations/ui-marccat/he.json
- translations/ui-marccat/hi_IN.json
- translations/ui-marccat/hu.json
- translations/ui-marccat/it_IT.json
- translations/ui-marccat/ja.json
- translations/ui-marccat/ko.json
- translations/ui-marccat/pl.json
- translations/ui-marccat/pt_BR.json
- translations/ui-marccat/pt_PT.json
- translations/ui-marccat/ru.json
- translations/ui-marccat/ur.json
- translations/ui-marccat/zh_CN.json
- translations/ui-marccat/zh_TW.json
> Update translation strings as of 20201119T214636

- translations/ui-marccat/ja.json
> Update translation strings as of 20201124T212804

- test/bigtest/interactors/action-menu.js
- test/bigtest/tests/action-menu-test.js
- test/bigtest/tests/browse-test.js
- test/bigtest/tests/record-duplicate-test.js
- test/bigtest/tests/record-edit-test.js
- test/bigtest/tests/record-test.js
- test/bigtest/tests/search-test.js
<a href="https://issues.folio.org/browse/UICAT-122"> UICAT-122 Errors when making Bibliographic/Authority searches </a>
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> Fix: test errors

- src/components/Cataloguing/Marc/Record/index.js
- src/components/Search/Panel/SearchPanel.js
- translations/ui-marccat/en.json
Fix actions messages
[UICAT-100 Edit authority record](https://issues.folio.org/browse/UICAT-100)
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UICAT-100 Edit authority record
